"""Amalgamate the pyrcr package into one standalone Python file.

The output (`pyrcr/full_rcr.py`) is a drop-in equivalent to
`cpp/src/full_rcr.cpp` — same role (a single file the user's larger
project can vendor) but for the Python port. Anything that's part of
the pyrcr package gets inlined; cross-module `stats.X` / `tables.X` /
`rejection.X` references are rewritten to local names.

When `pyrcr` changes, re-run this script to refresh `full_rcr.py`:

    python pyrcr/scripts/build_single_file.py

The output is fully self-contained: only depends on `numpy` and `scipy`
at runtime.
"""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SRC = REPO / "pyrcr" / "src" / "pyrcr"
DEST = REPO / "pyrcr" / "full_rcr.py"

# Module concat order. Carefully chosen so each module only references
# names defined earlier in the merged file:
#   1. tables.py    pure data — no dependencies inside the package
#   2. stats.py     numerical primitives — uses numpy only
#   3. nonparametric.py   class — uses numpy only
#   4. functional.py FunctionalForm + Priors — uses stats functions
#   5. rejection.py loops + dispatchers — uses tables, stats, FunctionalForm,
#                   NonParametric
#   6. api.py       RCR class + RCRResults — uses MuType, rejection.*
MODULE_ORDER = [
    "tables.py",
    "stats.py",
    "nonparametric.py",
    "functional.py",
    "rejection.py",
    "api.py",
]

# Substitutions to flatten the cross-module dotted references. Includes
# the `_stats` alias used inside FunctionalForm methods (via a local
# `from pyrcr import stats as _stats`).
DOT_SUBS = [
    (re.compile(r"\bstats\.([A-Za-z_]\w*)\b"), r"\1"),
    (re.compile(r"\b_stats\.([A-Za-z_]\w*)\b"), r"\1"),
    (re.compile(r"\btables\.([A-Za-z_]\w*)\b"), r"\1"),
    (re.compile(r"\brejection\.([A-Za-z_]\w*)\b"), r"\1"),
]

# Lines we strip from each module before concatenation.
STRIP_PATTERNS = [
    re.compile(r"^from __future__ import .*$"),
    re.compile(r"^from pyrcr import .*$"),
    re.compile(r"^from pyrcr\.[a-z_]+ import .*$"),
    re.compile(r"^import pyrcr\b.*$"),
    re.compile(r"^from pyrcr .*$"),
    # Function-local re-imports of pyrcr submodules (e.g. inside
    # FunctionalForm.get_nd_median: `from pyrcr import stats as _stats`).
    re.compile(r"^\s*from pyrcr import .*$"),
    re.compile(r"^\s*from pyrcr\.\w+ import .*$"),
    re.compile(r"^\s*import math as _math$"),  # local re-import in CF helpers
]

# Lines we collect once and emit at the top of the merged file.
IMPORT_PATTERNS = [
    re.compile(r"^import [a-zA-Z0-9_]+(?: as \w+)?$"),
    re.compile(r"^from [a-zA-Z0-9_.]+ import .*$"),
]


def _strip_leading_docstring(text: str) -> str:
    """Remove the first triple-quoted docstring at the top of the module
    (preserves the rest of the file)."""
    m = re.match(r'\s*("""(?:.|\n)*?"""|\'\'\'(?:.|\n)*?\'\'\')\s*\n', text)
    if m:
        return text[m.end():]
    return text


def _extract_module(path: Path) -> tuple[str, set[str]]:
    """Return (body, imports) for a module. The body has docstring +
    cross-module imports stripped, and `stats.X` / `tables.X` /
    `rejection.X` rewritten to bare `X`."""
    raw = path.read_text(encoding="utf-8")
    raw = _strip_leading_docstring(raw)

    body_lines: list[str] = []
    imports: set[str] = set()
    for line in raw.splitlines():
        stripped = line.strip()
        if any(p.match(stripped) for p in STRIP_PATTERNS):
            continue
        if any(p.match(stripped) for p in IMPORT_PATTERNS):
            # Don't import pyrcr modules; just collect plain external imports.
            if "pyrcr" in stripped:
                continue
            imports.add(stripped)
            continue
        body_lines.append(line)

    body = "\n".join(body_lines)
    for pattern, repl in DOT_SUBS:
        body = pattern.sub(repl, body)
    # `import math as _math` is used inside getLower68CF_w etc.; we
    # rewrite `_math.log10` to `math.log10` after stripping that import.
    body = re.sub(r"\b_math\.([A-Za-z_]\w*)\b", r"math.\1", body)
    # Rewrite docstring example code `pyrcr.X` → `X` so the docstrings in
    # the merged file are copy-pasteable without the pyrcr package. We
    # leave bare `pyrcr` (without a dotted attribute) intact — that
    # appears in prose descriptions that read fine either way.
    body = re.sub(r"\bpyrcr\.([A-Za-z_]\w*)", r"\1", body)
    return body, imports


HEADER = '''"""pyrcr — standalone single-file build.

Robust Chauvenet Rejection (RCR) — Python port of the C++ algorithm in
Maples et al. 2018 (https://arxiv.org/abs/1807.05276). This file is a
drop-in single-file artifact: vendor it into a larger project, no
`pip install pyrcr` required.

Generated by `pyrcr/scripts/build_single_file.py`. To refresh after
changes to the `pyrcr` package source, re-run that script — do NOT
hand-edit this file.

Runtime dependencies: numpy>=1.26, scipy>=1.11. Python>=3.11.

The public API mirrors the `pyrcr` package:

    RCR, RCRResults, RejectionTech, MuType
    FunctionalForm, FunctionalFormResults, Priors, PriorType
    NonParametric

See https://github.com/nickk124/RCR for the C++ reference implementation
and Maples et al. 2018 for the algorithm.
"""
from __future__ import annotations

'''


def main() -> None:
    bodies: list[tuple[str, str]] = []
    all_imports: set[str] = set()

    for name in MODULE_ORDER:
        path = SRC / name
        if not path.exists():
            raise FileNotFoundError(path)
        body, imports = _extract_module(path)
        bodies.append((name, body))
        all_imports |= imports

    # Stable-order the imports: standard library first, then third-party.
    std_lib = {"math", "itertools", "csv", "time", "json", "os", "sys",
               "hashlib", "warnings", "enum", "dataclasses", "typing",
               "collections", "functools", "pathlib"}
    sorted_imports: list[str] = []
    for imp in sorted(all_imports):
        sorted_imports.append(imp)

    pieces: list[str] = [HEADER]
    pieces.append("# fmt: off  # generated file; don't reformat\n\n")
    pieces.append("# ---- imports ----\n")
    for imp in sorted_imports:
        pieces.append(imp + "\n")
    pieces.append("\n")

    for name, body in bodies:
        pieces.append("# " + "=" * 76 + "\n")
        pieces.append(f"# Module: {name}\n")
        pieces.append("# " + "=" * 76 + "\n\n")
        pieces.append(body.rstrip("\n") + "\n\n")

    pieces.append('__all__ = [\n')
    for name in ["RCR", "RCRResults", "RejectionTech", "MuType",
                 "FunctionalForm", "FunctionalFormResults",
                 "Priors", "PriorType", "NonParametric"]:
        pieces.append(f'    "{name}",\n')
    pieces.append("]\n")
    pieces.append('__version__ = "0.1.0"\n')

    DEST.write_text("".join(pieces), encoding="utf-8")
    print(f"Wrote {DEST} ({DEST.stat().st_size:,} bytes, "
          f"{len(DEST.read_text(encoding='utf-8').splitlines()):,} lines)")


if __name__ == "__main__":
    main()
