"""One-shot extractor: pull the unity tables from cpp/src/RCR.cpp into
src/rcrpy/tables.py as numpy arrays.

The C++ `RCR::loadUnityTables()` function (cpp/src/RCR.cpp, ~lines 1564-4996)
contains ~3400 lines of hand-written float literal assignments into eight
arrays. We parse those assignments and emit a tables.py with the same
literals.

Why preserve the raw decimal text rather than recomputing or pretty-printing:
both Python's float-literal parser and C++'s strtod are IEEE 754
correctly-rounded for decimal-to-binary conversion, so identical decimal
text on both sides produces identical IEEE 754 doubles.

Run from the repository root:
    python rcrpy/scripts/extract_unity_tables.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SRC_CPP = REPO / "cpp" / "src" / "RCR.cpp"
DEST_PY = REPO / "rcrpy" / "src" / "rcrpy" / "tables.py"

EXPECTED_SIZES: dict[str, int] = {
    "ESUnity": 1001,
    "SSUnity": 1001,
    "LSUnity": 1001,
    "ESDLUnityCF": 101,
    "LSDLUnityCF": 101,
    "LS68UnityCF": 101,
    "SSDLUnityCF": 101,
}

EXPECTED_2D_SHAPES: dict[str, tuple[int, int]] = {
    "SSConstants": (2, 8),
}

NUM = r"[-+]?(?:\d+\.\d*|\.\d+|\d+)(?:[eE][-+]?\d+)?"
ASSIGN_1D = re.compile(rf"^\s*(\w+)\s*\[\s*(\d+)\s*\]\s*=\s*({NUM})\s*;")
ASSIGN_2D = re.compile(rf"^\s*(\w+)\s*\[\s*(\d+)\s*\]\s*\[\s*(\d+)\s*\]\s*=\s*({NUM})\s*;")


def find_loadUnityTables_bounds(text: str) -> tuple[int, int]:
    """Locate the function body byte offsets in the C++ source."""
    open_match = re.search(r"void\s+RCR::loadUnityTables\s*\(\s*\)\s*\n\s*\{", text)
    if not open_match:
        raise RuntimeError("Could not locate void RCR::loadUnityTables() definition")
    start = open_match.end()
    depth = 1
    i = start
    while i < len(text) and depth > 0:
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
        i += 1
    if depth != 0:
        raise RuntimeError("Unbalanced braces in loadUnityTables")
    return start, i - 1


def extract(cpp_text: str) -> tuple[dict[str, dict[int, str]], dict[str, dict[tuple[int, int], str]]]:
    start, end = find_loadUnityTables_bounds(cpp_text)
    body = cpp_text[start:end]

    flat: dict[str, dict[int, str]] = {name: {} for name in EXPECTED_SIZES}
    twoD: dict[str, dict[tuple[int, int], str]] = {name: {} for name in EXPECTED_2D_SHAPES}

    for raw_line in body.splitlines():
        line = raw_line.split("//", 1)[0]
        m2 = ASSIGN_2D.match(line)
        if m2:
            name, i, j, val = m2.group(1), int(m2.group(2)), int(m2.group(3)), m2.group(4)
            if name in twoD:
                twoD[name][(i, j)] = val
            continue
        m1 = ASSIGN_1D.match(line)
        if m1:
            name, idx, val = m1.group(1), int(m1.group(2)), m1.group(3)
            if name in flat:
                flat[name][idx] = val
    return flat, twoD


def build_arrays(flat, twoD):
    """Materialize each array as a list of literal strings, defaulting to '0.0'
    for indices the C++ left at the resize-default-zero value."""
    flat_arrays: dict[str, list[str]] = {}
    for name, size in EXPECTED_SIZES.items():
        values = ["0.0"] * size
        for idx, lit in flat[name].items():
            if idx >= size:
                raise RuntimeError(f"{name}[{idx}] exceeds expected size {size}")
            values[idx] = lit
        flat_arrays[name] = values

    twoD_arrays: dict[str, list[list[str]]] = {}
    for name, (rows, cols) in EXPECTED_2D_SHAPES.items():
        grid = [["0.0"] * cols for _ in range(rows)]
        for (i, j), lit in twoD[name].items():
            grid[i][j] = lit
        twoD_arrays[name] = grid

    return flat_arrays, twoD_arrays


def emit_python(flat_arrays, twoD_arrays) -> str:
    out: list[str] = []
    out.append('"""Unity tables for RCR, extracted verbatim from cpp/src/RCR.cpp.\n')
    out.append("Generated by rcrpy/scripts/extract_unity_tables.py.\n")
    out.append("DO NOT EDIT BY HAND — the SHA-256 of each array is asserted in\n")
    out.append("tests/test_tables.py to guard against drift.\n")
    out.append('"""\n')
    out.append("from __future__ import annotations\n\n")
    out.append("import numpy as np\n\n")

    for name in EXPECTED_SIZES:
        values = flat_arrays[name]
        out.append(f"{name} = np.array([\n")
        for chunk_start in range(0, len(values), 10):
            chunk = values[chunk_start:chunk_start + 10]
            out.append("    " + ", ".join(chunk) + ",\n")
        out.append("], dtype=np.float64)\n\n")

    for name in EXPECTED_2D_SHAPES:
        grid = twoD_arrays[name]
        out.append(f"{name} = np.array([\n")
        for row in grid:
            out.append("    [" + ", ".join(row) + "],\n")
        out.append("], dtype=np.float64)\n\n")

    return "".join(out)


def main() -> int:
    cpp_text = SRC_CPP.read_text(encoding="utf-8")
    flat, twoD = extract(cpp_text)

    for name, size in EXPECTED_SIZES.items():
        found = len(flat[name])
        max_idx = max(flat[name].keys(), default=-1)
        print(f"  {name:14s} found {found:4d} assignments, max index = {max_idx} (size {size})")
        if max_idx >= size:
            print(f"  !! {name} max index >= declared size", file=sys.stderr)
            return 1

    for name, (rows, cols) in EXPECTED_2D_SHAPES.items():
        found = len(twoD[name])
        print(f"  {name:14s} found {found} 2D assignments (expected up to {rows*cols})")

    flat_arrays, twoD_arrays = build_arrays(flat, twoD)
    py_source = emit_python(flat_arrays, twoD_arrays)
    DEST_PY.write_text(py_source, encoding="utf-8")
    print(f"\nWrote {DEST_PY} ({len(py_source):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
