

# ============================================================================
# Optional Numba acceleration (BIT-EXACT kernels; auto-enabled if numba is
# importable). Compiles the double-line core (fitDL_w) and its leaves — the
# inverse-erf x-vector, weighted m-finder, half-sample mode (both branches),
# 68th-percentile, FN ratio, and the C++-exact sequential sum — so the inner
# double-line runs end-to-end in nopython. Results are BIT-IDENTICAL to the
# pure-Python reference above (a parity battery's mu/sigma diff stays exactly
# 0). The transcendental kernels (inverf, getFNRatio) are bit-exact too: the
# `**2` exponent is threaded as a runtime function PARAMETER so Numba emits a
# real libm pow() (== CPython t**2) instead of folding to a multiply (~1 ULP
# drift). Numba's math.log/sqrt already match CPython's libm bit-for-bit.
#
# njit functions are MODULE-LEVEL with cache=True: numba can only cache
# top-level functions, and caching persists the compiled code to disk so a
# one-shot deployment doesn't recompile every kernel on every process (the
# first run compiles + caches; later runs load from disk).
#
# Falls back to pure Python if numba is absent. Set env RCRPY_NO_FAST=1 to
# force the pure-Python path (e.g. to use this file as the parity oracle).
# fitDL_w's get_fn_w (technique FN/CF model) stays in Python — it's the only
# transcendental that varies per technique and is called once per fitDL_w
# (bounded), not in the inner sum loops. Generated by build_single_file.py.
# ============================================================================
import os as _os

try:
    from numba import njit as _njit
except Exception:  # numba not installed -> stay on pure Python
    _njit = None


if _njit is not None and not _os.environ.get("RCRPY_NO_FAST"):

    @_njit(cache=True)
    def _rcrpy_seqsum(arr):
        s = 0.0
        for i in range(arr.shape[0]):
            s += arr[i]
        return s

    @_njit(cache=True)
    def _rcrpy_mfinder(low, high, last_x_under_one, increment, w, x, y):
        DBL_MAX = math.inf
        stop = False
        best_m = -1
        m_low = -1
        m_high = -1
        end_r = last_x_under_one + 1
        while not stop:
            min_error = DBL_MAX
            m = low
            while m < high:
                x_at_m = x[m]
                a = 0.0
                e = 0.0
                for i in range(m + 1):
                    wx = w[i] * x[i]
                    a += wx * x[i]
                    e += wx * y[i]
                for i in range(m + 1, end_r):
                    a += (x_at_m * x_at_m) * w[i]
                    e += (x_at_m * w[i]) * y[i]
                b = 0.0
                d = 0.0
                f = 0.0
                for i in range(m + 1, end_r):
                    diff = x[i] - x_at_m
                    b += (x_at_m * w[i]) * diff
                    d += (w[i] * diff) * diff
                    f += (w[i] * y[i]) * diff
                c = b
                if a != 0.0 and (d - c * b) != 0.0:
                    tau = (f - e * c / a) / (d - c * b / a)
                    sigma = (e - tau * b) / a
                    error = 0.0
                    for i in range(m + 1):
                        fl = sigma * x[i] - y[i]
                        error += (w[i] * fl) * fl
                    for i in range(m + 1, end_r):
                        diff = x[i] - x_at_m
                        fr = sigma * x_at_m + tau * diff - y[i]
                        error += (w[i] * fr) * fr
                    if error < min_error:
                        min_error = error
                        best_m = m
                        m_low = max(best_m - increment - 1, 1)
                        m_high = min(best_m + increment + 1, last_x_under_one)
                m += increment
            if increment > 1:
                increment = max(int(math.floor((m_high - m_low) / 6.36)), 1)
            else:
                stop = True
            low = m_low
            high = m_high
        if low == high:
            return low
        return best_m

    @_njit(cache=True)
    def _rcrpy_median(y):
        n = y.shape[0]
        if n <= 1:
            return y[0]
        high = n // 2
        low = high - 1
        total_sum = n
        if n % 2 == 0:
            running_sum = n / 2.0 + 0.5
        else:
            running_sum = n / 2.0
        return y[low] + (0.5 * total_sum - running_sum + 1.0) * (y[high] - y[low])

    @_njit(cache=True)
    def _rcrpy_hsm(y):
        REL_TOL = 1e-8
        n = y.shape[0]
        lo = 0
        hi = n - 1
        lo_in = -1
        hi_in = -1
        while lo != lo_in or hi != hi_in:
            lo_in = lo
            hi_in = hi
            size = hi - lo + 1
            half_window = size // 2
            if half_window == 0:
                break
            m = size - half_window
            min_dist = math.inf
            for i in range(m):
                dd = y[lo + half_window + i] - y[lo + i]
                if dd < min_dist:
                    min_dist = dd
            first_i = -1
            last_i = -1
            for i in range(m):
                dd = y[lo + half_window + i] - y[lo + i]
                if min_dist == 0.0:
                    tied = (dd == 0.0)
                else:
                    tied = abs(dd - min_dist) <= REL_TOL * abs(min_dist)
                if tied:
                    if first_i == -1:
                        first_i = i
                    last_i = i
            new_lo = first_i + lo
            new_hi = last_i + half_window + lo
            lo = new_lo
            hi = new_hi
        return _rcrpy_median(y[lo:hi + 1])

    @_njit(cache=True)
    def _rcrpy_isclose(a, b):
        if abs(a - b) < 2.2250738585072014e-308:
            return True
        d = abs(b) if abs(b) > abs(a) else abs(a)
        if d == 0.0:
            return True
        return abs((a - b) / d) < 1e-8

    @_njit(cache=True)
    def _rcrpy_hsm_w_window(w, y):
        n = y.shape[0]
        lower = 0
        upper = n - 1
        lower_in = -1
        upper_in = -1
        fl = -1
        fu = -1
        while lower != lower_in or upper != upper_in:
            lower_in = lower
            upper_in = upper
            size = upper - lower + 1
            if size <= 1:
                break
            min_dist = 999999.0
            hws = 0.0
            for i in range(lower, upper + 1):
                hws += w[i]
            hws *= 0.5
            s_vec = np.empty(size, dtype=np.float64)
            s = 0.5 * w[lower]
            s_vec[0] = s
            for j in range(1, size):
                s += w[lower + j - 1] * 0.5 + w[lower + j] * 0.5
                s_vec[j] = s
            for i in range(size):
                if s_vec[i] < hws or _rcrpy_isclose(s_vec[i], hws):
                    total = s_vec[i] + hws
                    k = i
                    while k < size and (s_vec[k] < total or _rcrpy_isclose(s_vec[k], total)):
                        k += 1
                    k -= 1
                    dd = abs(y[k + lower] - y[i + lower])
                    if _rcrpy_isclose(dd, min_dist):
                        if i + lower < fl:
                            fl = i + lower
                        if k + lower > fu:
                            fu = k + lower
                    elif dd < min_dist:
                        min_dist = dd
                        fl = i + lower
                        fu = k + lower
                if s_vec[i] > hws or _rcrpy_isclose(s_vec[i], hws):
                    total = s_vec[i] - hws
                    k = i
                    while k > -1 and (s_vec[k] > total or _rcrpy_isclose(s_vec[k], total)):
                        k -= 1
                    k += 1
                    dd = abs(y[i + lower] - y[k + lower])
                    if _rcrpy_isclose(dd, min_dist):
                        if k + lower < fl:
                            fl = k + lower
                        if i + lower > fu:
                            fu = i + lower
                    elif dd < min_dist:
                        min_dist = dd
                        fl = k + lower
                        fu = i + lower
            lower = fl
            upper = fu
        return lower, upper

    @_njit(cache=True)
    def _rcrpy_g68(y_sorted, w_sorted, total_sum):
        n = y_sorted.shape[0]
        if n <= 1:
            return y_sorted[0]
        sum_counter = 0
        running_sum = w_sorted[0] * 0.682689
        while running_sum < 0.682689 * total_sum:
            sum_counter += 1
            running_sum += (w_sorted[sum_counter - 1] * 0.317311
                            + w_sorted[sum_counter] * 0.682689)
        if sum_counter == 0:
            return y_sorted[0]
        denom = w_sorted[sum_counter - 1] * 0.317311 + w_sorted[sum_counter] * 0.682689
        return (y_sorted[sum_counter - 1]
                + (0.682689 * total_sum - (running_sum - denom)) / denom
                * (y_sorted[sum_counter] - y_sorted[sum_counter - 1]))

    @_njit(cache=True)
    def _rcrpy_inverf(x, e2):
        # e2 is a runtime PARAMETER -> real libm pow(t, 2.0) == CPython t**2.
        PI = 3.1415926535897932384626434
        inverf_mult = (8.0 * (PI - 3.0)) / (3 * PI * (4.0 - PI))
        sqrt2 = math.sqrt(2.0)
        x_log = math.log(1.0 - x * x)
        inner = math.pow(2.0 / (PI * inverf_mult) + x_log * 0.5, e2) - x_log / inverf_mult
        return sqrt2 * math.sqrt(-2.0 / (PI * inverf_mult) - x_log * 0.5 + math.sqrt(inner))

    @_njit(cache=True)
    def _rcrpy_getxvec(size, w, inv_w_sum, e2):
        x = np.empty(size, dtype=np.float64)
        s_sum = 0.682689 * w[0]
        x[0] = _rcrpy_inverf(s_sum * inv_w_sum, e2)
        for i in range(1, size):
            s_sum += 0.317311 * w[i - 1] + 0.682689 * w[i]
            x[i] = _rcrpy_inverf(s_sum * inv_w_sum, e2)
        return x

    @_njit(cache=True)
    def _rcrpy_fnratio_sumsq(w, counter, mean, e2):
        s = 0.0
        for i in range(counter):
            d = w[i] - mean
            s += math.pow(d, e2)
        return s

    @_njit(cache=True)
    def _rcrpy_fitdl_core(w, x, y):
        n = x.shape[0]
        if n == 1:
            amount = 0 if x[0] >= 1.0 else 1
        else:
            amount = 0
            while amount < n and x[amount] < 1.0:
                amount += 1
        num = 0.0
        den = 0.0
        for i in range(amount):
            wx = w[i] * x[i]
            num += wx * y[i]
            den += wx * x[i]
        single_line_fit = num / den
        if n < 4:
            return single_line_fit, single_line_fit, 0.0, True
        m = _rcrpy_mfinder(1, amount - 1, amount - 1, max(int(n / 6.36), 1), w, x, y)
        x_at_m = x[m]
        a = 0.0
        e = 0.0
        for i in range(m + 1):
            wx = w[i] * x[i]
            a += wx * x[i]
            e += wx * y[i]
        for i in range(m + 1, amount):
            a += (x_at_m * x_at_m) * w[i]
            e += (x_at_m * w[i]) * y[i]
        b = 0.0
        d = 0.0
        f = 0.0
        for i in range(m + 1, amount):
            diff = x[i] - x_at_m
            b += (x_at_m * w[i]) * diff
            d += (w[i] * diff) * diff
            f += (w[i] * y[i]) * diff
        c = b
        tau = (f - e * c / a) / (d - c * b / a)
        sigma = (e - tau * b) / a
        dle = 0.0
        for i in range(m + 1):
            fl = sigma * x[i] - y[i]
            dle += (w[i] * fl) * fl
        for i in range(m + 1, amount):
            diff = x[i] - x_at_m
            fr = sigma * x_at_m + tau * diff - y[i]
            dle += (w[i] * fr) * fr
        sle = 0.0
        for i in range(amount):
            ef = single_line_fit * x[i] - y[i]
            sle += (w[i] * ef) * ef
        numd = sle - dle
        if dle != 0.0:
            delta = numd / dle
        elif numd > 0.0:
            delta = math.inf
        elif numd < 0.0:
            delta = -math.inf
        else:
            delta = math.nan
        if sigma < 0:
            sigma = 1e-10
        return sigma, single_line_fit, delta, False

    # ---- plain-Python wrappers that swap in for the reference functions ----
    def _rcrpy_cpp_seqsum(arr):
        a = np.ascontiguousarray(arr, np.float64)
        if a.shape[0] == 0:
            return 0.0
        return float(_rcrpy_seqsum(a))

    def _rcrpy_mFinder_w(low, high, last_x_under_one, increment, w, x, y):
        return _rcrpy_mfinder(low, high, last_x_under_one, increment,
                              np.ascontiguousarray(w, np.float64),
                              np.ascontiguousarray(x, np.float64),
                              np.ascontiguousarray(y, np.float64))

    def _rcrpy_halfSampleMode(y):
        return float(_rcrpy_hsm(np.ascontiguousarray(y, np.float64)))

    def _rcrpy_halfSampleMode_w(w, y):
        w = np.ascontiguousarray(w, np.float64)
        y = np.ascontiguousarray(y, np.float64)
        lo, hi = _rcrpy_hsm_w_window(w, y)
        return float(getMedian_w(w[lo:hi + 1], y[lo:hi + 1]))

    def _rcrpy_get68th_w(w, y):
        idx = np.argsort(y, kind="stable")
        ys = np.ascontiguousarray(y[idx], np.float64)
        ws = np.ascontiguousarray(w[idx], np.float64)
        return float(_rcrpy_g68(ys, ws, float(np.sum(ws))))

    def _rcrpy_getXVec_w(size, w):
        w = np.ascontiguousarray(w, np.float64)
        return _rcrpy_getxvec(size, w, 1.0 / float(np.sum(w)), 2.0)

    def _rcrpy_getFNRatio(x, w):
        counter = int(np.searchsorted(x, 1.0, side="left"))
        if counter == 0:
            return math.nan
        w = np.ascontiguousarray(w, np.float64)
        mean = float(np.sum(w[:counter])) / counter
        st_dev = _cpp_sqrt_div(_rcrpy_fnratio_sumsq(w, counter, mean, 2.0), counter - 1)
        return math.nan if mean == 0.0 else st_dev / mean

    def _rcrpy_fitDL_w(counter, w, x, y, get_fn_w):
        w = np.ascontiguousarray(w, np.float64)
        x = np.ascontiguousarray(x, np.float64)
        y = np.ascontiguousarray(y, np.float64)
        sigma, single_line_fit, delta, short = _rcrpy_fitdl_core(w, x, y)
        if short:
            return single_line_fit
        if delta < get_fn_w(int(counter), x, w):
            return single_line_fit
        return sigma

    # Warm up (compile) off the hot path, then swap module globals. Wrapped in
    # try/except so a latent JIT issue can NEVER turn into an unconditional
    # import crash for consumers (e.g. cornifer): on any failure we leave the
    # pure-Python globals untouched. (Note: a hard segfault is uncatchable, so
    # the real safety is that no njit function is recursive — see _R4_psum.)
    try:
        _rw = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
        _rx = np.array([0.2, 0.5, 0.9, 1.3, 2.0])
        _ry = np.array([1.0, 2.0, 2.0, 3.0, 9.0])
        _rcrpy_cpp_seqsum(_rx)
        _rcrpy_mFinder_w(1, 3, 4, 3, _rw, _rx, _rw)
        _rcrpy_halfSampleMode(_ry)
        _rcrpy_halfSampleMode_w(_rw, _ry)
        _rcrpy_get68th_w(_rw, _rx)
        _rcrpy_getXVec_w(5, _rw)
        _rcrpy_getFNRatio(_rx, _rw)
        _rcrpy_fitdl_core(_rw, _rx, _rw)

        _cpp_seqsum = _rcrpy_cpp_seqsum
        mFinder_w = _rcrpy_mFinder_w
        halfSampleMode = _rcrpy_halfSampleMode
        halfSampleMode_w = _rcrpy_halfSampleMode_w
        get68th_w = _rcrpy_get68th_w
        getXVec_w = _rcrpy_getXVec_w
        getFNRatio = _rcrpy_getFNRatio
        fitDL_w = _rcrpy_fitDL_w
    except Exception:  # noqa: BLE001 - JIT unavailable/failed -> pure Python
        pass

    _R4_LS = np.ascontiguousarray(LSUnity, np.float64)          # FN unity (n<1001)
    _R4_LSDL = np.ascontiguousarray(LSDLUnityCF, np.float64)    # DL CF unity (n<101)
    # exponent arrays passed as runtime params so numba emits real libm pow()
    _R4_ECF = np.array([0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 2.4716, -0.65])  # [_,2,3,4,5,6,2.4716,-0.65]
    _R4_EFN = np.array([0.0, 2.0, 3.0, 4.0, 5.0, 6.0, 0.1765])
    _R4_DBL_MIN = float(np.finfo(np.float64).tiny)


    @_njit(cache=True, error_model="numpy")
    def _R4_psum(a):
        # numpy pairwise sum, ITERATIVE (explicit stack). MUST stay
        # non-recursive: a recursive @njit(cache=True) (or a cached caller of
        # one) segfaults on cache LOAD (known numba bug -> full_rcr import
        # access violation). Bit-identical to numpy np.sum (0/8000).
        n0 = a.shape[0]
        if n0 == 0:
            return 0.0
        lo_st = np.empty(128, np.int64)
        n_st = np.empty(128, np.int64)
        st_st = np.empty(128, np.int64)
        res = np.empty(128, np.float64)
        sp = 1
        rp = 0
        lo_st[0] = 0
        n_st[0] = n0
        st_st[0] = 0
        while sp > 0:
            sp -= 1
            lo = lo_st[sp]
            n = n_st[sp]
            state = st_st[sp]
            if state == 1:
                r = res[rp - 2] + res[rp - 1]
                rp -= 2
                res[rp] = r
                rp += 1
            elif n < 8:
                s = 0.0
                for i in range(n):
                    s += a[lo + i]
                res[rp] = s
                rp += 1
            elif n <= 128:
                r0 = a[lo]; r1 = a[lo+1]; r2 = a[lo+2]; r3 = a[lo+3]
                r4 = a[lo+4]; r5 = a[lo+5]; r6 = a[lo+6]; r7 = a[lo+7]
                i = 8
                while i < n - (n % 8):
                    r0 += a[lo+i]; r1 += a[lo+i+1]; r2 += a[lo+i+2]; r3 += a[lo+i+3]
                    r4 += a[lo+i+4]; r5 += a[lo+i+5]; r6 += a[lo+i+6]; r7 += a[lo+i+7]
                    i += 8
                s = ((r0+r1)+(r2+r3)) + ((r4+r5)+(r6+r7))
                for j in range(n - (n % 8), n):
                    s += a[lo+j]
                res[rp] = s
                rp += 1
            else:
                n2 = n // 2
                n2 -= n2 % 8
                lo_st[sp] = lo; n_st[sp] = n; st_st[sp] = 1; sp += 1
                lo_st[sp] = lo + n2; n_st[sp] = n - n2; st_st[sp] = 0; sp += 1
                lo_st[sp] = lo; n_st[sp] = n2; st_st[sp] = 0; sp += 1
        return res[0]


    @_njit(cache=True, error_model="numpy")
    def _R4_sqrtdiv(top, denom):
        if denom > 0.0:
            frac = top / denom
        elif denom == 0.0:
            frac = math.inf if top > 0.0 else math.nan
        else:
            frac = top / denom
        if frac != frac or frac < 0.0:
            return math.nan
        return math.sqrt(frac)


    @_njit(cache=True, error_model="numpy")
    def _R4_isclose(a, b):
        # isEqual_vec_scalar semantics: |a-b|<DBL_MIN OR |a-b|/max(|a|,|b|) <= 1e-8
        diff = abs(a - b)
        if diff < _R4_DBL_MIN:
            return True
        larger = abs(a) if abs(a) > abs(b) else abs(b)
        if larger <= 0.0:
            return False
        return diff / larger <= 1e-8


    @_njit(cache=True, error_model="numpy")
    def _R4_mean_w(w, y):
        n = w.shape[0]
        wy = np.empty(n, np.float64)
        for i in range(n):
            wy[i] = w[i] * y[i]
        return _R4_psum(wy) / _R4_psum(w)


    @_njit(cache=True, error_model="numpy")
    def _R4_median_w(w, y):
        # w,y already sorted ascending by y (caller does mergesort)
        n = y.shape[0]
        if n <= 1:
            return y[0]
        total_sum = _R4_psum(w)
        sum_counter = 0
        running_sum = w[0] * 0.5
        while running_sum < 0.5 * total_sum:
            sum_counter += 1
            running_sum += w[sum_counter - 1] * 0.5 + w[sum_counter] * 0.5
        if sum_counter == 0:
            return y[0]
        denom = w[sum_counter - 1] * 0.5 + w[sum_counter] * 0.5
        return (y[sum_counter - 1]
                + (0.5 * total_sum - (running_sum - denom)) / denom
                * (y[sum_counter] - y[sum_counter - 1]))


    @_njit(cache=True, error_model="numpy")
    def _R4_stdev_w(delta, w, y):
        n = w.shape[0]
        t = np.empty(n, np.float64)
        ws = np.empty(n, np.float64)
        for i in range(n):
            t[i] = (w[i] * y[i]) * y[i]
            ws[i] = w[i] * w[i]
        top = _R4_psum(t)
        w_sum = _R4_psum(w)
        w_sum_sq = _R4_psum(ws)
        return _R4_sqrtdiv(top, w_sum - delta * w_sum_sq / w_sum)


    @_njit(cache=True, error_model="numpy")
    def _R4_get68th_w(w, y):
        # sort y ascending (stable), w along; then 68.27 percentile walk
        order = np.argsort(y, kind="mergesort")
        ys = y[order]
        ws = w[order]
        n = ys.shape[0]
        if n <= 1:
            return ys[0]
        total_sum = _R4_psum(ws)
        sum_counter = 0
        running_sum = ws[0] * 0.682689
        while running_sum < 0.682689 * total_sum:
            sum_counter += 1
            running_sum += ws[sum_counter - 1] * 0.317311 + ws[sum_counter] * 0.682689
        if sum_counter == 0:
            return ys[0]
        denom = ws[sum_counter - 1] * 0.317311 + ws[sum_counter] * 0.682689
        return (ys[sum_counter - 1]
                + (0.682689 * total_sum - (running_sum - denom)) / denom
                * (ys[sum_counter] - ys[sum_counter - 1]))


    @_njit(cache=True, error_model="numpy")
    def _R4_hsm_w(w, y):
        # y,w already sorted ascending by y. window search (both branches) + median.
        n = y.shape[0]
        lower = 0
        upper = n - 1
        lower_in = -1
        upper_in = -1
        fl = -1
        fu = -1
        while lower != lower_in or upper != upper_in:
            lower_in = lower
            upper_in = upper
            size = upper - lower + 1
            if size <= 1:
                break
            min_dist = 999999.0
            hws = 0.0
            for i in range(lower, upper + 1):
                hws += w[i]
            hws *= 0.5
            s_vec = np.empty(size, np.float64)
            s = 0.5 * w[lower]
            s_vec[0] = s
            for j in range(1, size):
                s += w[lower + j - 1] * 0.5 + w[lower + j] * 0.5
                s_vec[j] = s
            for i in range(size):
                if s_vec[i] < hws or _R4_isclose(s_vec[i], hws):
                    total = s_vec[i] + hws
                    k = i
                    while k < size and (s_vec[k] < total or _R4_isclose(s_vec[k], total)):
                        k += 1
                    k -= 1
                    dd = abs(y[k + lower] - y[i + lower])
                    if _R4_isclose(dd, min_dist):
                        if i + lower < fl:
                            fl = i + lower
                        if k + lower > fu:
                            fu = k + lower
                    elif dd < min_dist:
                        min_dist = dd
                        fl = i + lower
                        fu = k + lower
                if s_vec[i] > hws or _R4_isclose(s_vec[i], hws):
                    total = s_vec[i] - hws
                    k = i
                    while k > -1 and (s_vec[k] > total or _R4_isclose(s_vec[k], total)):
                        k -= 1
                    k += 1
                    dd = abs(y[i + lower] - y[k + lower])
                    if _R4_isclose(dd, min_dist):
                        if k + lower < fl:
                            fl = k + lower
                        if i + lower > fu:
                            fu = i + lower
                    elif dd < min_dist:
                        min_dist = dd
                        fl = k + lower
                        fu = i + lower
            lower = fl
            upper = fu
        return _R4_median_w(w[lower:upper + 1], y[lower:upper + 1])


    @_njit(cache=True, error_model="numpy")
    def _R4_mu_w(mu_code, w, y):
        if mu_code == 0:   # MEAN
            return _R4_mean_w(w, y)
        order = np.argsort(y, kind="mergesort")
        ws = w[order]
        ys = y[order]
        if mu_code == 1:   # MEDIAN
            return _R4_median_w(ws, ys)
        return _R4_hsm_w(ws, ys)   # MODE


    @_njit(cache=True, error_model="numpy")
    def _R4_cfratio(w):
        n = w.shape[0]
        mean = _R4_psum(w) / n
        diffs = np.empty(n, np.float64)
        for i in range(n):
            d = w[i] - mean
            diffs[i] = d * d
        st_dev = _R4_sqrtdiv(_R4_psum(diffs), n - 1)
        return math.nan if mean == 0.0 else st_dev / mean


    @_njit(cache=True, error_model="numpy")
    def _R4_fnratio(x, w, e2):
        n = x.shape[0]
        counter = 0
        while counter < n and x[counter] < 1.0:
            counter += 1
        if counter == 0:
            return math.nan
        mean = _R4_psum(w[:counter]) / counter
        s = 0.0
        for i in range(counter):
            d = w[i] - mean
            s += math.pow(d, e2)
        st_dev = _R4_sqrtdiv(s, counter - 1)
        return math.nan if mean == 0.0 else st_dev / mean


    @_njit(cache=True, error_model="numpy")
    def _R4_pow10pow10(z):
        return math.pow(10.0, math.pow(10.0, z))


    @_njit(cache=True, error_model="numpy")
    def _R4_lowerdlcf(n, w, E):
        x = _R4_cfratio(w)
        if n < 101:
            y1 = 1.0 / _R4_LSDL[n]
        else:
            y1 = 1.0 / (1.0 - 3.3245 * math.pow(n, E[7]))
        if x == 0.0:
            return y1
        logx = math.log10(x)
        logn = math.log10(n)
        sign = -1.0 if n % 2 else 1.0
        if n == 2:
            b1 = 1.08149771508934; a1 = -0.398375456223868
        elif n == 3:
            b1 = 1.51433669748424; a1 = -1.10939332689999
        elif n == 4:
            return y1
        elif n == 5:
            b1 = 0.339404852185332; a1 = -1.1445790996528
        elif 5 < n < 21:
            b1 = (43.179 * math.pow(logn, E[5]) - 331.85 * math.pow(logn, E[4])
                  + 968.25 * math.pow(logn, E[3]) - 1399.1 * math.pow(logn, E[2])
                  + 1070.7 * math.pow(logn, E[1]) - 415.81 * logn + 65.002
                  + sign * 0.1365 * math.pow(logn, E[6]))
            a1 = (-0.2683 * math.pow(logn, E[3]) + 1.9174 * math.pow(logn, E[2])
                  - 5.062 * math.pow(logn, E[1]) + 5.452 * logn - 2.9999)
        elif 20 < n < 101:
            b1 = 1.5144 * logn - 0.0448 + sign * 0.1365 * math.pow(logn, E[6])
            a1 = (-0.2683 * math.pow(logn, E[3]) + 1.9174 * math.pow(logn, E[2])
                  - 5.062 * math.pow(logn, E[1]) + 5.452 * logn - 2.9999)
        else:
            b1 = 2.988077 + sign * 0.753032
            a1 = -0.4282 * logn - 0.4412
        return y1 * _R4_pow10pow10(a1 + b1 * logx)


    @_njit(cache=True, error_model="numpy")
    def _R4_lowerfn(n, x, w, E, e2):
        ratio = _R4_fnratio(x, w, e2)
        if n < 1001:
            y1 = _R4_LS[n]
        else:
            y1 = math.pow(1.3399, math.pow(n, E[6]))   # E[6]=0.1765
        if ratio == 0.0:
            return y1
        logx = math.log10(ratio)
        logn = math.log10(n)
        if n == 5:
            y1 = 36.8534
            b1 = -0.300348560626506; a1 = -0.0828207791627729
            return y1 * _R4_pow10pow10(a1 + b1 * logx)
        if n == 6:
            b1 = -0.244262599183892; a1 = -0.267502535686502
            return y1 * _R4_pow10pow10(a1 + b1 * logx)
        if n == 7:
            b1 = -0.409677351330214; a1 = -0.558845927943435
            return y1 * _R4_pow10pow10(a1 + b1 * logx)
        if n == 8:
            b1 = -0.488354948027081; a1 = -0.889342857411619
            return y1 * _R4_pow10pow10(a1 + b1 * logx)
        if 8 < n < 1001:
            # E layout: E[1]=2, E[2]=3, E[3]=4, E[4]=5, E[5]=6 (same as _R4_lowerdlcf)
            b1 = (0.1462 * math.pow(logn, E[2]) - 4.2139 * math.pow(logn, E[1])
                  + 14.366 * logn - 10.658)
            a1 = (-0.541 * math.pow(logn, E[4]) + 4.6943 * math.pow(logn, E[3])
                  - 15.407 * math.pow(logn, E[2]) + 21.875 * math.pow(logn, E[1])
                  - 11.211 * logn - 0.3798)
            b2 = 26.945 * math.pow(logn, E[2]) - 221.42 * math.pow(logn, E[1]) + 606.91 * logn - 553.89
            a2 = 18.149 * math.pow(logn, E[2]) - 149.27 * math.pow(logn, E[1]) + 410.15 * logn - 378.47
            if n <= 264 or (n < 568 and (a1 + b1 * logx > a2 + b2 * logx)):
                return y1 * _R4_pow10pow10(a1 + b1 * logx)
            return y1 / _R4_pow10pow10(a2 + b2 * logx)
        b1 = 0.0424 * logn + 1.4479
        a1 = 0.3861 * logn - 2.5852
        return y1 / _R4_pow10pow10(a1 + b1 * logx)


    @_njit(cache=True, error_model="numpy")
    def _R4_erfc(x, e16):
        x = x / math.sqrt(2.0)
        inner = (1.0 + x*(0.0705230784 + x*(0.0422820123 + x*(0.0092705272
                + x*(0.0001520143 + x*(0.0002765672 + 0.0000430638*x))))))
        return 1.0 / math.pow(inner, e16)


    @_njit(cache=True, error_model="numpy")
    def _R4_distinct(flags, y):
        n = y.shape[0]
        i = 0
        while i < n and not flags[i]:
            i += 1
        if i >= n:
            return False
        a = y[i]
        b = a
        i += 1
        found_b = False
        while i < n:
            if flags[i] and not _R4_isclose(y[i], a):
                b = y[i]
                found_b = True
                break
            i += 1
        if not found_b:
            return False
        i += 1
        while i < n:
            if flags[i] and not _R4_isclose(y[i], a) and not _R4_isclose(y[i], b):
                return True
            i += 1
        return False


    @_njit(cache=True, error_model="numpy")
    def _R4_count_under_one(x):
        n = x.shape[0]
        if n == 1:
            return 0 if x[0] >= 1.0 else 1
        c = 0
        while c < n and x[c] < 1.0:
            c += 1
        return c


    @_njit(cache=True, error_model="numpy")
    def _R4_xvec(size, w, inv_w_sum, e2):
        x = np.empty(size, np.float64)
        s = 0.682689 * w[0]
        PI = 3.1415926535897932384626434
        mlt = (8.0 * (PI - 3.0)) / (3 * PI * (4.0 - PI))
        s2 = math.sqrt(2.0)
        v = s * inv_w_sum
        xl = math.log(1.0 - v * v)
        x[0] = s2 * math.sqrt(-2.0/(PI*mlt) - xl*0.5 + math.sqrt(math.pow(2.0/(PI*mlt)+xl*0.5, e2) - xl/mlt))
        for i in range(1, size):
            s += 0.317311 * w[i - 1] + 0.682689 * w[i]
            v = s * inv_w_sum
            xl = math.log(1.0 - v * v)
            x[i] = s2 * math.sqrt(-2.0/(PI*mlt) - xl*0.5 + math.sqrt(math.pow(2.0/(PI*mlt)+xl*0.5, e2) - xl/mlt))
        return x


    @_njit(cache=True, error_model="numpy")
    def _R4_fitsl(w, x, y, end):
        num = 0.0
        den = 0.0
        for i in range(end):
            wx = w[i] * x[i]
            num += wx * y[i]
            den += wx * x[i]
        return num / den


    @_njit(cache=True, error_model="numpy")
    def _R4_fitdl(counter, w, x, y, E, e2):
        # x is the getXVec output; y is the (sorted) diff array; returns sigma.
        n = x.shape[0]
        amount = _R4_count_under_one(x)
        single_line_fit = _R4_fitsl(w, x, y, amount)
        if n < 4:
            return single_line_fit
        m = _R4_mfinder(1, amount - 1, amount - 1, max(int(n / 6.36), 1), w, x, y)
        x_at_m = x[m]
        a = 0.0; e = 0.0
        for i in range(m + 1):
            wx = w[i] * x[i]
            a += wx * x[i]
            e += wx * y[i]
        for i in range(m + 1, amount):
            a += (x_at_m * x_at_m) * w[i]
            e += (x_at_m * w[i]) * y[i]
        b = 0.0; d = 0.0; f = 0.0
        for i in range(m + 1, amount):
            diff = x[i] - x_at_m
            b += (x_at_m * w[i]) * diff
            d += (w[i] * diff) * diff
            f += (w[i] * y[i]) * diff
        c = b
        tau = (f - e * c / a) / (d - c * b / a)
        sigma = (e - tau * b) / a
        dle = 0.0
        for i in range(m + 1):
            fl = sigma * x[i] - y[i]
            dle += (w[i] * fl) * fl
        for i in range(m + 1, amount):
            diff = x[i] - x_at_m
            fr = sigma * x_at_m + tau * diff - y[i]
            dle += (w[i] * fr) * fr
        sle = 0.0
        for i in range(amount):
            ef = single_line_fit * x[i] - y[i]
            sle += (w[i] * ef) * ef
        numd = sle - dle
        if dle != 0.0:
            delta = numd / dle
        elif numd > 0.0:
            delta = math.inf
        elif numd < 0.0:
            delta = -math.inf
        else:
            delta = math.nan
        if sigma < 0:
            sigma = 1e-10
        if delta < _R4_lowerfn(counter, x, w, E, e2):
            sigma = single_line_fit
        return sigma


    @_njit(cache=True, error_model="numpy")
    def _R4_mfinder(low, high, last_x_under_one, increment, w, x, y):
        DBL_MAX = math.inf
        stop = False
        best_m = -1
        m_low = -1
        m_high = -1
        end_r = last_x_under_one + 1
        while not stop:
            min_error = DBL_MAX
            m = low
            while m < high:
                x_at_m = x[m]
                a = 0.0; e = 0.0
                for i in range(m + 1):
                    wx = w[i] * x[i]
                    a += wx * x[i]
                    e += wx * y[i]
                for i in range(m + 1, end_r):
                    a += (x_at_m * x_at_m) * w[i]
                    e += (x_at_m * w[i]) * y[i]
                b = 0.0; d = 0.0; f = 0.0
                for i in range(m + 1, end_r):
                    diff = x[i] - x_at_m
                    b += (x_at_m * w[i]) * diff
                    d += (w[i] * diff) * diff
                    f += (w[i] * y[i]) * diff
                c = b
                if a != 0.0 and (d - c * b) != 0.0:
                    tau = (f - e * c / a) / (d - c * b / a)
                    sigma = (e - tau * b) / a
                    error = 0.0
                    for i in range(m + 1):
                        fl = sigma * x[i] - y[i]
                        error += (w[i] * fl) * fl
                    for i in range(m + 1, end_r):
                        diff = x[i] - x_at_m
                        fr = sigma * x_at_m + tau * diff - y[i]
                        error += (w[i] * fr) * fr
                    if error < min_error:
                        min_error = error
                        best_m = m
                        m_low = max(best_m - increment - 1, 1)
                        m_high = min(best_m + increment + 1, last_x_under_one)
                m += increment
            if increment > 1:
                increment = max(int(math.floor((m_high - m_low) / 6.36)), 1)
            else:
                stop = True
            low = m_low
            high = m_high
        if low == high:
            return low
        return best_m


    @_njit(cache=True, error_model="numpy")
    def _R4_sigma_lower(sigma_code, w, diff, delta, counter, E, e2):
        # 0=STANDARD_DEVIATION, 1=SIXTY_EIGHTH, 2=DOUBLE_LINE
        if sigma_code == 0:
            return _R4_stdev_w(delta / 2.0, w, diff)
        if sigma_code == 1:
            return _R4_get68th_w(w, diff)
        # DOUBLE_LINE
        x = _R4_xvec(diff.shape[0], w, 1.0 / _R4_psum(w), e2)
        x_below = _R4_count_under_one(x)
        if x_below > 2:
            return _R4_fitdl(counter, w, x, diff, E, e2)
        if x_below > 1:
            return _R4_fitsl(w, x, diff, _R4_count_under_one(x))
        return _R4_get68th_w(w, diff)


    @_njit(cache=True, error_model="numpy")
    def _R4_iter_lower_w(w, y, flags, mu_code, sigma_code, delta, ECF, EFN, e2, e16):
        n = y.shape[0]
        mu = -1.0; sigma = -1.0; st_dev = -1.0; sba = -1.0; sbe = -1.0
        floor = _R4_DBL_MIN
        while True:
            cnt = 0
            for i in range(n):
                if flags[i]:
                    cnt += 1
            idxs = np.empty(cnt, np.int64)
            tw = np.empty(cnt, np.float64)
            ty = np.empty(cnt, np.float64)
            k = 0
            for i in range(n):
                if flags[i]:
                    idxs[k] = i; tw[k] = w[i]; ty[k] = y[i]; k += 1
            true_count = cnt
            mu = _R4_mu_w(mu_code, tw, ty)
            # diff, argmax (first max)
            max_local = 0
            max_val = abs(ty[0] - mu)
            for i in range(1, cnt):
                dv = abs(ty[i] - mu)
                if dv > max_val:
                    max_val = dv
                    max_local = i
            max_index = idxs[max_local]
            # tie-split: counts
            nb = 0; na = 0
            for i in range(cnt):
                ic = _R4_isclose(ty[i], mu)
                if ty[i] < mu or ic:
                    nb += 1
                if ty[i] > mu or ic:
                    na += 1
            diff_b = np.empty(nb, np.float64); wb = np.empty(nb, np.float64)
            diff_a = np.empty(na, np.float64); wa = np.empty(na, np.float64)
            ib = 0; ia = 0
            for i in range(cnt):
                ic = _R4_isclose(ty[i], mu)
                dv = abs(ty[i] - mu)
                wv = 0.5 * tw[i] if ic else tw[i]
                if ty[i] < mu or ic:
                    diff_b[ib] = dv; wb[ib] = wv; ib += 1
                if ty[i] > mu or ic:
                    diff_a[ia] = dv; wa[ia] = wv; ia += 1
            nonzero_below = nb > 0
            nonzero_above = na > 0
            if nonzero_below:
                ob = np.argsort(diff_b, kind="mergesort")
                diff_b = diff_b[ob]; wb = wb[ob]
            if nonzero_above:
                oa = np.argsort(diff_a, kind="mergesort")
                diff_a = diff_a[oa]; wa = wa[oa]
            n_correction = _R4_lowerdlcf(true_count, tw, ECF)
            if nonzero_above and nonzero_below:
                sba = _R4_sigma_lower(sigma_code, wa, diff_a, delta, true_count, EFN, e2)
                sbe = _R4_sigma_lower(sigma_code, wb, diff_b, delta, true_count, EFN, e2)
                st_dev = sba if sba < sbe else sbe
                sigma = st_dev * n_correction
            elif nonzero_above:
                st_dev = _R4_sigma_lower(sigma_code, wa, diff_a, delta, true_count, EFN, e2)
                sba = st_dev
                sigma = st_dev * n_correction
            elif nonzero_below:
                st_dev = _R4_sigma_lower(sigma_code, wb, diff_b, delta, true_count, EFN, e2)
                sbe = st_dev
                sigma = st_dev * n_correction
            ratio = max_val / (sigma if sigma > 0 else floor)
            if _R4_distinct(flags, y) and true_count * _R4_erfc(ratio, e16) < 0.5:
                flags[max_index] = False
            else:
                break
        return mu, sigma, st_dev, sbe, sba


    @_njit(cache=True, error_model="numpy")
    def _R4_bulk_sigma_lower(w, diff, counter, E, e2):
        x = _R4_xvec(diff.shape[0], w, 1.0 / _R4_psum(w), e2)
        xb = _R4_count_under_one(x)
        if xb > 2:
            a = _R4_fitdl(counter, w, x, diff, E, e2)
            b = _R4_fitsl(w, x, diff, xb)
            return a if a > b else b
        if xb > 1:
            return _R4_fitsl(w, x, diff, xb)
        return _R4_get68th_w(w, diff)


    @_njit(cache=True, error_model="numpy")
    def _R4_bulk_reject(flags, indices_sorted, ratios_sorted, y, e16):
        no_rej = True
        size = ratios_sorted.shape[0]
        i = size - 1
        while i >= 0 and _R4_distinct(flags, y) and size * _R4_erfc(ratios_sorted[i], e16) < 0.5:
            flags[indices_sorted[i]] = False
            no_rej = False
            i -= 1
        return no_rej


    @_njit(cache=True, error_model="numpy")
    def _R4_bulk_lower_w(w, y, flags, mu_code, delta, ECF, EFN, e2, e16):
        n = y.shape[0]
        mu = -1.0
        sigma = -1.0
        while True:
            cnt = 0
            for i in range(n):
                if flags[i]:
                    cnt += 1
            idxs = np.empty(cnt, np.int64)
            tw = np.empty(cnt, np.float64)
            ty = np.empty(cnt, np.float64)
            k = 0
            for i in range(n):
                if flags[i]:
                    idxs[k] = i; tw[k] = w[i]; ty[k] = y[i]; k += 1
            true_count = cnt
            mu = _R4_mu_w(mu_code, tw, ty)
            # diff_hold (all points, in trueY order)
            dh = np.empty(cnt, np.float64)
            for i in range(cnt):
                dh[i] = abs(ty[i] - mu)
            # below/above counts (C++ list semantics: isEqual->both; elif >mu->above; else->below)
            nb = 0; na = 0
            for i in range(cnt):
                if _R4_isclose(ty[i], mu):
                    nb += 1; na += 1
                elif ty[i] > mu:
                    na += 1
                else:
                    nb += 1
            diff_b = np.empty(nb, np.float64); wb = np.empty(nb, np.float64)
            diff_a = np.empty(na, np.float64); wa = np.empty(na, np.float64)
            ib = 0; ia = 0
            for i in range(cnt):
                hold = abs(ty[i] - mu)
                if _R4_isclose(ty[i], mu):
                    diff_b[ib] = hold; wb[ib] = 0.5 * tw[i]; ib += 1
                    diff_a[ia] = hold; wa[ia] = 0.5 * tw[i]; ia += 1
                elif ty[i] > mu:
                    diff_a[ia] = hold; wa[ia] = tw[i]; ia += 1
                else:
                    diff_b[ib] = hold; wb[ib] = tw[i]; ib += 1
            # sort diff_hold stable -> indices_sorted
            sh = np.argsort(dh, kind="mergesort")
            idx_sorted = idxs[sh]
            dh_sorted = dh[sh]
            nonzero_below = nb > 0
            nonzero_above = na > 0
            if nonzero_below:
                ob = np.argsort(diff_b, kind="mergesort"); diff_b = diff_b[ob]; wb = wb[ob]
            if nonzero_above:
                oa = np.argsort(diff_a, kind="mergesort"); diff_a = diff_a[oa]; wa = wa[oa]
            ncf = _R4_lowerdlcf(true_count, tw, ECF)
            if nonzero_above and nonzero_below:
                sb = _R4_bulk_sigma_lower(wb, diff_b, true_count, EFN, e2)
                sa = _R4_bulk_sigma_lower(wa, diff_a, true_count, EFN, e2)
                sigma = (sb if sb < sa else sa) * ncf
            elif nonzero_above:
                sigma = _R4_bulk_sigma_lower(wa, diff_a, true_count, EFN, e2) * ncf
            elif nonzero_below:
                sigma = _R4_bulk_sigma_lower(wb, diff_b, true_count, EFN, e2) * ncf
            ratios = np.empty(cnt, np.float64)
            for i in range(cnt):
                ratios[i] = dh_sorted[i] / sigma   # IEEE: /0 -> inf/nan, handled by erfc
            if _R4_bulk_reject(flags, idx_sorted, ratios, y, e16):
                break
        return mu, sigma

    # ---- Round 4: full weighted lower-sigma driver swap (LS_MODE_DL config) ----
    _R4_dlcf = getLowerDLCF_w
    _R4_ref_iter = iterativeLowerSigmaRCR_w
    _R4_ref_bulk = bulkLowerSigmaRCR_w
    _R4_MU = {MuTech.MEAN: 0, MuTech.MEDIAN: 1, MuTech.MODE: 2}
    _R4_SG = {SigmaTech.STANDARD_DEVIATION: 0, SigmaTech.SIXTY_EIGHTH_PERCENTILE: 1, SigmaTech.DOUBLE_LINE: 2}

    def _R4_iter_fast(w, y, flags, mu_tech, sigma_tech, delta, n_correct_fn,
                      non_parametric_model=None, parametric_model=None):
        if (non_parametric_model is None and parametric_model is None
                and n_correct_fn is _R4_dlcf and mu_tech in _R4_MU and sigma_tech in _R4_SG):
            mu, sigma, sd, sbe, sba = _R4_iter_lower_w(
                np.ascontiguousarray(w, np.float64), np.ascontiguousarray(y, np.float64),
                flags, _R4_MU[mu_tech], _R4_SG[sigma_tech], float(delta), _R4_ECF, _R4_EFN, 2.0, 16.0)
            return {"mu": mu, "sigma": sigma, "st_dev": sd, "st_dev_below": sbe, "st_dev_above": sba}
        return _R4_ref_iter(w, y, flags, mu_tech, sigma_tech, delta, n_correct_fn,
                            non_parametric_model, parametric_model)

    def _R4_bulk_fast(w, y, flags, mu_tech, n_correct_fn,
                      non_parametric_model=None, parametric_model=None):
        if (non_parametric_model is None and parametric_model is None
                and n_correct_fn is _R4_dlcf and mu_tech in _R4_MU):
            mu, sigma = _R4_bulk_lower_w(
                np.ascontiguousarray(w, np.float64), np.ascontiguousarray(y, np.float64),
                flags, _R4_MU[mu_tech], 1.0, _R4_ECF, _R4_EFN, 2.0, 16.0)
            return {"mu": mu, "sigma": sigma}
        return _R4_ref_bulk(w, y, flags, mu_tech, n_correct_fn,
                            non_parametric_model, parametric_model)

    # Guarded like the R1-R3 group: any warm-up/compile failure leaves the
    # pure-Python drivers in place rather than crashing the import.
    try:
        _R4_iter_lower_w(np.ones(20), np.arange(20.0), np.ones(20, np.bool_), 2, 2, 1.0, _R4_ECF, _R4_EFN, 2.0, 16.0)
        _R4_bulk_lower_w(np.ones(20), np.arange(20.0), np.ones(20, np.bool_), 2, 1.0, _R4_ECF, _R4_EFN, 2.0, 16.0)
        iterativeLowerSigmaRCR_w = _R4_iter_fast
        bulkLowerSigmaRCR_w = _R4_bulk_fast
    except Exception:  # noqa: BLE001 - JIT failed -> pure-Python drivers
        pass

    @_njit(cache=True, error_model="numpy")
    def _R5_lowerdlcf(n, E):
        if n < 101:
            return 1.0 / _R4_LSDL[n]
        return 1.0 / (1.0 - 3.3245 * (n ** E[7]))   # n**-0.65; E param -> real libm pow


    @_njit(cache=True, error_model="numpy")
    def _R5_iter_lower(y, flags, mu_code, sigma_code, delta, ECF, EFN, e2, e16):
        n = y.shape[0]
        mu = -1.0; sigma = -1.0; st_dev = -1.0; sba = -1.0; sbe = -1.0
        while True:
            cnt = 0
            for i in range(n):
                if flags[i]:
                    cnt += 1
            idxs = np.empty(cnt, np.int64); ty = np.empty(cnt, np.float64)
            k = 0
            for i in range(n):
                if flags[i]:
                    idxs[k] = i; ty[k] = y[i]; k += 1
            true_count = cnt
            ones = np.ones(cnt, np.float64)
            mu = _R4_mu_w(mu_code, ones, ty)
            max_local = 0; max_val = abs(ty[0] - mu)
            for i in range(1, cnt):
                dv = abs(ty[i] - mu)
                if dv > max_val:
                    max_val = dv; max_local = i
            max_index = idxs[max_local]
            last_eq = -1
            for i in range(cnt):
                if _R4_isclose(ty[i], mu):
                    last_eq = i
            nb = 0; na = 0
            for i in range(cnt):
                ic = _R4_isclose(ty[i], mu)
                if ty[i] < mu or ic:
                    nb += 1
                if ty[i] > mu or ic:
                    na += 1
            diff_b = np.empty(nb, np.float64); wb = np.ones(nb, np.float64)
            diff_a = np.empty(na, np.float64); wa = np.ones(na, np.float64)
            ib = 0; ia = 0; below_split = -1; above_split = -1
            for i in range(cnt):
                ic = _R4_isclose(ty[i], mu); dv = abs(ty[i] - mu)
                if ty[i] < mu or ic:
                    diff_b[ib] = dv
                    if i == last_eq:
                        below_split = ib
                    ib += 1
                if ty[i] > mu or ic:
                    diff_a[ia] = dv
                    if i == last_eq:
                        above_split = ia
                    ia += 1
            if last_eq != -1:
                if below_split >= 0:
                    wb[below_split] = 0.5
                if above_split >= 0:
                    wa[above_split] = 0.5
            nonzero_below = nb > 0; nonzero_above = na > 0
            if nonzero_below:
                ob = np.argsort(diff_b, kind="mergesort"); diff_b = diff_b[ob]; wb = wb[ob]
            if nonzero_above:
                oa = np.argsort(diff_a, kind="mergesort"); diff_a = diff_a[oa]; wa = wa[oa]
            ncf = _R5_lowerdlcf(true_count, ECF)
            if nonzero_above and nonzero_below:
                sba = _R4_sigma_lower(sigma_code, wa, diff_a, delta, true_count, EFN, e2)
                sbe = _R4_sigma_lower(sigma_code, wb, diff_b, delta, true_count, EFN, e2)
                st_dev = sba if sba < sbe else sbe
                sigma = st_dev * ncf
            elif nonzero_above:
                st_dev = _R4_sigma_lower(sigma_code, wa, diff_a, delta, true_count, EFN, e2)
                sba = st_dev; sigma = st_dev * ncf
            elif nonzero_below:
                st_dev = _R4_sigma_lower(sigma_code, wb, diff_b, delta, true_count, EFN, e2)
                sbe = st_dev; sigma = st_dev * ncf
            ratio = max_val / (sigma if sigma > 0.0 else _R4_DBL_MIN)
            if _R4_distinct(flags, y) and true_count * _R4_erfc(ratio, e16) < 0.5:
                flags[max_index] = False
            else:
                break
        return mu, sigma, st_dev, sbe, sba


    @_njit(cache=True, error_model="numpy")
    def _R5_bulk_lower(y, flags, mu_code, ECF, EFN, e2, e16):
        n = y.shape[0]
        counter = n   # PINNED to original size (C++ quirk)
        mu = -1.0; sigma = -1.0
        while True:
            cnt = 0
            for i in range(n):
                if flags[i]:
                    cnt += 1
            idxs = np.empty(cnt, np.int64); ty = np.empty(cnt, np.float64)
            k = 0
            for i in range(n):
                if flags[i]:
                    idxs[k] = i; ty[k] = y[i]; k += 1
            true_count = cnt
            ones = np.ones(cnt, np.float64)
            mu = _R4_mu_w(mu_code, ones, ty)
            dh = np.empty(cnt, np.float64)
            for i in range(cnt):
                dh[i] = abs(ty[i] - mu)
            last_eq = -1
            for i in range(cnt):
                if _R4_isclose(ty[i], mu):
                    last_eq = i
            nb = 0; na = 0
            for i in range(cnt):
                ic = _R4_isclose(ty[i], mu)
                if ty[i] < mu or ic:
                    nb += 1
                if ty[i] > mu or ic:
                    na += 1
            diff_b = np.empty(nb, np.float64); wb = np.ones(nb, np.float64)
            diff_a = np.empty(na, np.float64); wa = np.ones(na, np.float64)
            ib = 0; ia = 0; below_split = -1; above_split = -1
            for i in range(cnt):
                ic = _R4_isclose(ty[i], mu); dv = abs(ty[i] - mu)
                if ty[i] < mu or ic:
                    diff_b[ib] = dv
                    if i == last_eq:
                        below_split = ib
                    ib += 1
                if ty[i] > mu or ic:
                    diff_a[ia] = dv
                    if i == last_eq:
                        above_split = ia
                    ia += 1
            if last_eq != -1:
                if below_split >= 0:
                    wb[below_split] = 0.5
                if above_split >= 0:
                    wa[above_split] = 0.5
            sh = np.argsort(dh, kind="mergesort")
            idx_sorted = idxs[sh]; dh_sorted = dh[sh]
            nonzero_below = nb > 0; nonzero_above = na > 0
            if nonzero_below:
                ob = np.argsort(diff_b, kind="mergesort"); diff_b = diff_b[ob]; wb = wb[ob]
            if nonzero_above:
                oa = np.argsort(diff_a, kind="mergesort"); diff_a = diff_a[oa]; wa = wa[oa]
            ncf = _R5_lowerdlcf(counter, ECF)
            if nonzero_above and nonzero_below:
                sb = _R4_bulk_sigma_lower(wb, diff_b, counter, EFN, e2)
                sa = _R4_bulk_sigma_lower(wa, diff_a, counter, EFN, e2)
                sigma = (sb if sb < sa else sa) * ncf
            elif nonzero_above:
                sigma = _R4_bulk_sigma_lower(wa, diff_a, counter, EFN, e2) * ncf
            elif nonzero_below:
                sigma = _R4_bulk_sigma_lower(wb, diff_b, counter, EFN, e2) * ncf
            ratios = np.empty(cnt, np.float64)
            for i in range(cnt):
                ratios[i] = dh_sorted[i] / sigma
            if _R4_bulk_reject(flags, idx_sorted, ratios, y, e16):
                break
        return mu, sigma

    # ---- Round 5: swap UNWEIGHTED lower-sigma drivers (LS_MODE_DL) ----
    _R5_ref_iter = iterativeLowerSigmaRCR
    _R5_ref_bulk = bulkLowerSigmaRCR
    _R5_dlcf = getLowerDLCF

    def _R5_iter_fast(y, flags, mu_tech, sigma_tech, delta, n_correct_fn,
                      non_parametric_model=None, parametric_model=None):
        if (non_parametric_model is None and parametric_model is None
                and n_correct_fn is _R5_dlcf and mu_tech in _R4_MU and sigma_tech in _R4_SG):
            mu, sigma, sd, sbe, sba = _R5_iter_lower(
                np.ascontiguousarray(y, np.float64), flags,
                _R4_MU[mu_tech], _R4_SG[sigma_tech], float(delta), _R4_ECF, _R4_EFN, 2.0, 16.0)
            return {"mu": mu, "sigma": sigma, "st_dev": sd,
                    "st_dev_above": sba, "st_dev_below": sbe}
        return _R5_ref_iter(y, flags, mu_tech, sigma_tech, delta, n_correct_fn,
                            non_parametric_model, parametric_model)

    def _R5_bulk_fast(y, flags, mu_tech, n_correct_fn,
                      non_parametric_model=None, parametric_model=None):
        if (non_parametric_model is None and parametric_model is None
                and n_correct_fn is _R5_dlcf and mu_tech in _R4_MU):
            mu, sigma = _R5_bulk_lower(
                np.ascontiguousarray(y, np.float64), flags, _R4_MU[mu_tech], _R4_ECF, _R4_EFN, 2.0, 16.0)
            return {"mu": mu, "sigma": sigma}
        return _R5_ref_bulk(y, flags, mu_tech, n_correct_fn,
                            non_parametric_model, parametric_model)

    try:
        _R5_iter_lower(np.arange(20.0), np.ones(20, np.bool_), 2, 2, 1.0, _R4_ECF, _R4_EFN, 2.0, 16.0)
        _R5_bulk_lower(np.arange(20.0), np.ones(20, np.bool_), 2, _R4_ECF, _R4_EFN, 2.0, 16.0)
        iterativeLowerSigmaRCR = _R5_iter_fast
        bulkLowerSigmaRCR = _R5_bulk_fast
    except Exception:  # noqa: BLE001
        pass
